#pragma once

#define BBKEY_MAXANGLE TEXT("MaxAngle")
#define BBKEY_TARGET TEXT("Target")
#define BBKEY_TARGETANGLE TEXT("TargetAngle")
#define BBKEY_RELOADTIME TEXT("ReloadTime")
#define BBKEY_ISRELOAD TEXT("IsReload")
#define BBKEY_ISLOOKAT TEXT("IsLookAt")
#define BBKEY_POINT TEXT("Point")
#define BBKEY_POINTANGLE TEXT("PointAngle")
#define BBKEY_ATTACKTYPE TEXT("AttackType")
#define BBKEY_INITROTATION TEXT("InitRotation")
#define BBKEY_ROTATIONSPEED TEXT("RotationSpeed")
#define BBKEY_ATTACKRANGE TEXT("AttackRange")
#define BBKEY_MOUSEANGLE TEXT("MouseAngle")
#define BBKEY_BATTLESHIPANGLE TEXT("BattleShipAngle")